# Generated by Django 5.1.4 on 2024-12-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MicroserviceBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('instrument', models.CharField(max_length=50)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent', models.IntegerField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stream_session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('ERROR', 'Error')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('levels_data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
