# Generated by Django 5.1.4 on 2025-01-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_microservicebot_stream_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microservicebot',
            name='account_currency',
            field=models.CharField(choices=[('PLN', 'PLN'), ('USD', 'USD')], default='PLN', max_length=3),
        ),
        migrations.AddField(
            model_name='microservicebot',
            name='asset_currency',
            field=models.CharField(choices=[('PLN', 'PLN'), ('USD', 'USD'), ('EUR', 'EUR')], default='PLN', max_length=3),
        ),
    ]
