# Generated by Django 5.1.4 on 2025-01-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_microservicebot_account_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microservicebot',
            name='min_price',
        ),
    ]
