# Generated by Django 5.1.4 on 2025-02-11 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d510', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botd10',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='botd10',
            name='percent',
        ),
        migrations.AddField(
            model_name='botd10',
            name='band_percent',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AddField(
            model_name='botd10',
            name='levels_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botd10',
            name='rise_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='botd10',
            name='step_percent',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='botd10',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='TradeD10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=10)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='d510.botd10')),
            ],
        ),
    ]
