# Generated by Django 5.1.4 on 2024-12-20 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XTBConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xtb_id', models.CharField(max_length=50, verbose_name='XTB ID')),
                ('password', models.BinaryField(verbose_name='Encrypted Password')),
                ('is_live', models.BooleanField(default=False, verbose_name='Live Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xtb_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='XTBAccount',
        ),
    ]
