# Generated by Django 5.1.4 on 2024-12-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bot_stream_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='microservice_bot_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
