# Generated by Django 5.1.4 on 2025-01-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_bot_microservice_bot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot',
            name='percent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('ERROR', 'Error')], default='NEW', max_length=20),
        ),
    ]
