# Generated by Django 5.1.4 on 2025-01-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_bot_capital_alter_bot_max_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='strategy_type',
            field=models.CharField(choices=[('XTB51015', 'XTB51015')], default='XTB51015', max_length=20),
        ),
    ]
