# Generated by Django 5.1.4 on 2025-01-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_bot_strategy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
