# Generated by Django 5.1.4 on 2025-01-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bot_finished_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='min_price',
        ),
    ]
