# Generated by Django 5.1.4 on 2025-01-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_bot_min_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='strategy_type',
        ),
        migrations.AddField(
            model_name='bot',
            name='broker_type',
            field=models.CharField(choices=[('XTB', 'XTB Broker'), ('BNB', 'Binance')], default='XTB', max_length=3),
        ),
    ]
