# Generated by Django 5.1.4 on 2025-02-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_bot_strategy_type_bot_broker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='broker_type',
            field=models.CharField(choices=[('XTB', 'XTB Broker'), ('BNB', 'Binance'), ('D10', 'D510XTB')], default='XTB', max_length=3),
        ),
    ]
