# Generated by Django 5.1.4 on 2025-03-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onesignal_player_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OneSignal Player ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='push_notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Enable Push Notifications'),
        ),
    ]
