"""
Django settings for stockstorm_project project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-br7*sac60)7rpbb=78iwl60%!v#h4*t*+yd^hs@6&wn1_x*z!#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'home.middleware.LiveStatusMiddleware',
]

ROOT_URLCONF = 'stockstorm_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "home/templates"],  # Dodaj tę linię
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'stockstorm_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'server',  # Nazwa bazy danych
        'USER': 'root',     # Nazwa użytkownika MySQL
        'PASSWORD': 'Polskikaktus9036.',     # Hasło użytkownika
        'HOST': '127.0.0.1',           # Lokalny serwer MySQL
        'PORT': '3306',                # Domyślny port MySQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'home/static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/dashboard/'  # Przekierowanie po udanym logowaniu
LOGOUT_REDIRECT_URL = '/'  # Przekierowanie po wylogowaniu


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

MICROSERVICE_API_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MzA5NzU4LCJpYXQiOjE3MzUzMDk0NTgsImp0aSI6IjJiNjk1MTdlYTM2MzQ5MjE4MThkNzg3ZjNlMjVkMDk5IiwidXNlcl9pZCI6Nn0.Nm0mZBwvWRsZQOtLBJ3XxYT7ZgsdVLZscLvRehuYZJU"
MICROSERVICE_API_TOKEN2 = "8ee87711af0f17dbec69ec1bfae12ccde2f6f012"
MICROSERVICE_URL = "http://127.0.0.1:8001/create_bot/"
MICROSERVICE_URL2 = "http://127.0.0.1:8005"



# Adres RabbitMQ jako brokera
CELERY_BROKER_URL = 'amqp://guest:guest@localhost:5672//'

# Backend wyników wyłączony (jeśli nie potrzebujesz wyników)
CELERY_RESULT_BACKEND = None

# Akceptowane formaty danych
CELERY_ACCEPT_CONTENT = ['json']

# Serializacja zadań
CELERY_TASK_SERIALIZER = 'json'

# Strefa czasowa Celery
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Śledzenie rozpoczętych zadań
CELERY_TASK_TRACK_STARTED = True

# Limit czasu dla zadania (opcjonalne, np. 30 minut)
CELERY_TASK_TIME_LIMIT = 30 * 60

# Limit czasu dla twardego zakończenia zadania (jeśli miękki limit nie zadziała)
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60

# Maksymalna liczba powtórzeń zadania (opcjonalne)
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# Logowanie zadań
CELERY_WORKER_LOG_FORMAT = "[%(asctime)s: %(levelname)s/%(processName)s] %(message)s"
CELERY_WORKER_REDIRECT_STDOUTS_LEVEL = 'DEBUG'

# Konfiguracja Celery Beat (Harmonogram zadań)
CELERY_BEAT_SCHEDULE = {
    'ping-xtb-every-10-seconds': {
        'task': 'home.tasks.ping_xtb',
        'schedule': 10.0,  # Co 10 sekund
    },
    'sync-xtb-session-ids-every-10-seconds': {
        'task': 'home.tasks.sync_xtb_session_ids',
        'schedule': 10.0,  # Co 10 sekund
    },
}